- hosts: localhost
  gather_facts: false
  vars:
    privx_url: https://privx.example.com
    secret_name: your_secret
  tasks:
    - name: Read secret using OAuth (env vars)
      debug:
        msg: "{{ lookup('sshcom.privx.privx_secret',
                        secret_name,
                        url=privx_url) }}"
    - name: Read secret using OAuth (explicit params)
      debug:
        msg: "{{ lookup('sshcom.privx.privx_secret',
                        secret_name,
                        url=privx_url,
                        client_id=lookup('env', 'PRIVX_CLIENT_ID'),
                        client_secret=lookup('env', 'PRIVX_CLIENT_SECRET'),
                        oauth_client_id=lookup('env', 'PRIVX_OAUTH_CLIENT_ID'),
                        oauth_client_secret=lookup('env', 'PRIVX_OAUTH_CLIENT_SECRET')) }}"
    - name: Read secret using module
      sshcom.privx.privx_secret_info:
        path: "{{ secret_name }}"
        url: "{{ privx_url }}"
      register: result
    - name: Show secret
      debug:
        var: result.secret
