- hosts: localhost
  gather_facts: false
  vars:
    privx_url: https://privx.example.com
    privx_token: "{{ lookup('env', 'PRIVX_TOKEN') }}"
  tasks:
    - name: Read secret using JWT token
      debug:
        msg: "{{ lookup('sshcom.privx.privx_secret',
                        'example',
                        url=privx_url,
                        token=privx_token) }}"
